oppgave-client
navikt/hag-oppgave-client pull request #3
Opened 2024-09-24 10:55 UTC by mettok

2024-09-24 11:50 UTC, b162214 commented on src/main/kotlin/no/nav/helsearbeidsgiver/oppgave/Oppgave.kt
> +object LocalDateSerializer : KSerializer<LocalDate> {
Jeg tenker at det er bedre å ta i bruk https://github.com/navikt/helsearbeidsgiver-utils
for dette. evt legge til det der hvis det mangler feks.

2024-09-24 11:50 UTC, b162214 commented on src/main/kotlin/no/nav/helsearbeidsgiver/oppgave/Oppgave.kt
> +object LocalDateSerializer : KSerializer<LocalDate> {
eksempel på bruk :
https://github.com/navikt/helsearbeidsgiver-inntektsmelding/blob/39be7430530bf6dd82238390390956babdc5526a/felles/src/main/kotlin/no/nav/helsearbeidsgiver/felles/domene/Arbeidsforhold.kt

2024-09-24 11:50 UTC, b162214 commented on gradle.properties
> +kotlinSerializationVersion=1.6.0
jeg tror det finnes nyere versjon av denne.

2024-09-24 12:20 UTC, b162214 requested changes
Var hovedsakelig de to sakene jeg stusset over.
Også kan det andre komme i en ny pr som diskutert.

2024-09-25 12:11 UTC, b162214 commented on src/main/kotlin/no/nav/helsearbeidsgiver/oppgave/OppgaveClient.kt
> +class OppgaveClientImpl(
Tenkte ikke over dette i går.
Men er det nødvendig å fortsette med dette patternet?
Det er jo bare en implementasjon uanset.
Så kan vel kanskje bare være en klasse uten interface?

2024-09-26 05:30 UTC, mettok commented on src/main/kotlin/no/nav/helsearbeidsgiver/oppgave/OppgaveClient.kt
> +class OppgaveClientImpl(
Ja vi bruker ikke interfacet til noe spesielt. Jeg fjerner det

2024-09-26 11:52 UTC, b162214 approved these changes

2024-09-26 12:15 UTC, merged